name: Build SunoneAimbot2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Aimbot-Release
          path: build/Release/*.exe
