name: Build SunoneAimbot2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装编译工具与依赖
        run: |
          choco install nuget
          nuget install Microsoft.ML.OnnxRuntime.DirectML -OutputDirectory packages

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake 配置
        run: cmake -B build -G "Visual Studio 17 2022"

      - name: 编译 Release 版本
        run: cmake --build build --config Release

      - name: 上传成品EXE
        uses: actions/upload-artifact@v4
        with:
          name: Aimbot成品
          path: build/Release/*.exe
